# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_FDR <- function(p, FDR = 0.1) {
    .Call('DEEE_Cpp_FDR', PACKAGE = 'DEEE', p, FDR)
}

Cpp_fvalue <- function(myData) {
    .Call('DEEE_Cpp_fvalue', PACKAGE = 'DEEE', myData)
}

Cpp_fvalues <- function(lm) {
    .Call('DEEE_Cpp_fvalues', PACKAGE = 'DEEE', lm)
}

Cpp_plotMat <- function(nfig, figcol, xshrink = 1.0, yshrink = 1.0) {
    .Call('DEEE_Cpp_plotMat', PACKAGE = 'DEEE', nfig, figcol, xshrink, yshrink)
}

Cpp_median <- function(lm) {
    .Call('DEEE_Cpp_median', PACKAGE = 'DEEE', lm)
}

Cpp_MAD <- function(l) {
    .Call('DEEE_Cpp_MAD', PACKAGE = 'DEEE', l)
}

#' The order of a vector
#'
#' \code{Cpp_order} returns the order of a given vector. It has the same purpose as 
#' \code{\link[base]{order}}, but is implemented with Cpp and much faster.
#'
#' @param vec A vector of numerics.
#' @return A vector of integers containing the order the given vector is returned.
#' @export
Cpp_order <- function(vec) {
    .Call('DEEE_Cpp_order', PACKAGE = 'DEEE', vec)
}

#' The rank of a vector
#'
#' \code{Cpp_rank} returns the order of a given vector. It has the same purpose as
#' \code{\link[base]{rank}}, but is implemented with Cpp and much faster.
#'
#' @param vec A vector of numerics.
#' @return A vector of integers containing the rank the given vector is returned.
#' @export
Cpp_rank <- function(vec) {
    .Call('DEEE_Cpp_rank', PACKAGE = 'DEEE', vec)
}

MedWVY <- function(mat, ref) {
    .Call('DEEE_MedWVY', PACKAGE = 'DEEE', mat, ref)
}

MADWVY <- function(mat, ref) {
    .Call('DEEE_MADWVY', PACKAGE = 'DEEE', mat, ref)
}

MatRankit <- function(mat) {
    .Call('DEEE_MatRankit', PACKAGE = 'DEEE', mat)
}

